


to_vegetariandict = {
  'boneless pork loin chop': 'tofurkey',
  'pork': 'tofurkey'
}

['1 tablespoon butter', 
'1 (6 ounce) boneless pork loin chop, cut into small pieces', 
'1/4 cup chopped carrot', 
'1/4 cup chopped broccoli', 
'1 green onion, chopped', 
'1 egg, beaten', 
'1 cup cold cooked rice', 
'1/4 cup frozen peas', 
'1 1/2 tablespoons soy sauce', 
'1/8 teaspoon garlic powder', 
'1/8 teaspoon ground ginger']
['Melt butter in a large non-stick skillet over medium heat. Cook and stir pork, carrot, broccoli, peas, and green onion in melted butter until pork is cooked through, 7 to 10 minutes. Remove pork mixture to a bowl and return skillet to medium heat.', 
'Scramble egg in the skillet until completely set. Return the pork mixture to the skillet. Stir rice, peas, soy sauce, garlic powder, and ground ginger into the pork mixture; cook and stir until heated through, 7 to 10 minutes.']

#original to healthy
to_healthydict={
	'beef': 'turkey',
	'fried chicken': 'grilled chicken',
	'turkey burger': 'veggie burger',
	'burger': 'mushroom',
	'pork': 'jackfruit',
	'boneless':'',
	'plain':'',
	'meat':'meat/veggie',
	'pork chops':'jackfruit',
	# 'turkey': 'tofurkey',
	'chicken': 'tempeh',
	'ground beef': 'ground turkey',
	'ground pork': 'ground jackfruit',
	'bacon': 'turkey bacon',
	'sausage': 'turkey sausage',
	'white rice': 'brown rice',
	'rice': 'brown rice',
	'pasta': 'whole-grain pasta',
	'spaghetti': 'whole-grain spaghetti',
	'bread': 'whole-grain bread',
	'penne': 'whole-grain penne',
	'flour tortilla': 'corn tortilla',
	'tortilla' : 'lettuce',
	'butter': 'margarine',
	'sour cream': 'greek yogurt',
	'croutons': 'almonds',
	'sugar': 'stevia',
	'flour': 'coconut flour',
	'salt': 'himalayan salt',
	'breadcrumbs': 'chia seeds',
	'bread crumbs': 'chia seeds',
	'bread crumb': 'chia seed',
	'chocolate chips': 'cocoa nibs',
	'iceberg': 'romaine',
	'ranch dressing': 'olive oil',
	'ranch' :'olive oil',
	'peanut butter': 'almond butter',
	'milk' : 'almond milk',
	# 'oil' : 'vegetable oil',
	'soy sauce':'coconut aminos',
	'frying' : 'grilling or baking',
	'fried':'grilled or baked',
	'fry':'grill or bake',
	'cornstarch':'wheat flour',
	'chocolate':'dark-chocolate'
}

# original to nonhealthy
to_unhealthydict={
	'sugar ':'corn syrup',
	'olive oil':'lard',
	'coconut oil':'lard',
	'vegetable oil':'lard',
	' oil' : 'lard',
	'plain':'glazed',
	'bread':'donut',
	'milk' : 'heavy cream',
	'veggie burger':'burger',
	'veggie':'beef',
	'water':'sugarwater',
	'dark chocolate':'milk chocolate',
	# 'bake':'fry',
	'grill':'fry',
	'red pepper':'pepperoni',
	'salt':'salt coated in oil',
	'carrots':'licorice',
	'carrot':'licorice',
	'flour':'cornstarch',
	'egg':'artificial egg',
	# 'green onion':' fried green onion',
	# 'yellow onion':'fried yellow onion',
	# ''
	'onion':'fried onion',
	'green pepper':'fried green pepper'

}

#style of cuisine: Sicilian Cuisine (Sicily in Italy)
to_siciliandict={
	'meatsauce': 'ragu',
	'tomato': 'Pachino tomato',
	'noodles': 'spaghetti',
	'broth': 'soup',
	'tilapi': 'sea bream',
	'salmon': 'bluefin tuna',
	'blueberry':'mulberry',
	'cilantro': 'mint',
	'shark': 'swordfish',
	'marlin': 'swordfish',
	'carp':'sea bream',
	'donut': 'cannoli',
	'red wine': 'Marsala',
	'wine': 'Marsala',
	'green bean': 'fava bean',
	'lima bean': 'fava bean',
	'salt': 'sea salt',
	'herring': 'sardines', 
	'pesto': 'zogghiu',
	'quinoa': 'couscous', 
	'vegetable oil': 'olive oil',
	'cocunut oil': 'olive oil',
	'regular oil':'olive oil',
	'any oil':'olive oil',
	'ground beef': 'ground veal',
	'ground turkey':'ground veal',
	'beef' :'lamb',
	'celery': 'fennels',
	'sorbert': 'granita',
	'flour': 'durum wheat/semolina flour',
	'orange': 'moro orange',
	'provolone': 'caciocavallo',
	'mozerella' :'caciocavallo',
	'american': 'pecorino',
	'chedder' :'caciocavallo',
	'parmesan': 'ricotta',
	'colby':'ricotta',
	'gruyere' :'maiorchino',
	'cottage': 'ricotta',
	'cream cheese' :'ricotta',
	'blue cheese' : 'gorgonzola',
	'meunster' : 'ragusano',
	'guda' : 'canestrato',
	'swiss': 'tuma',
	'feta':'ricotta',
	'garlic': 'Nubia Red Garlic',
	'chocolate': 'Modica chocolate',
	'lemon' :'Siracusa lemon',
	# 'grill': 'fry',
	'ice cream':'gelato',
	'garam masala':'cinnamon',
	'masala curry':'ragu',	
	'curry':'ragu',
	'tumeric':'saffron',
	'basmati rice':'orzo',
	'white rice':'orzo',
	'brown rice':'orzo',
	'cardamom pods':'fava beans',
	'green onion':'Giarratana Onion',
	'yellow onion':"Giarratana Onion",
	'red onion': 'Giarratana Onion',
	'onion':'Giarratana Onion',
	'iceberg lettuce':'arugula',
	'romaine lettuce':'arugula',
	'lettuce':'arugula',
	'soy sauce':'olive oil or Salmoriglio',
	'mushroom':'porcini mushroom',
	'tamarind pulp':'chickpeas',
	'tamarind':'chickpeas',
	'coriander':'menta',
}
