

to_vegetariandict = {
  'boneless pork loin chop': 'tofurkey',
  'pork': 'tofurkey'
}

#original to healthy
to_healthydict={
	'beef': 'turkey',
	'fried chicken': 'grilled chicken',
	'turkey burger': 'veggie burger',
	'burger': 'mushroom',
	'pork': 'jackfruit',
	'boneless':'',
	'plain':'',
	'meat':'meat/veggie',
	'pork chops':'jackfruit',
	# 'turkey': 'tofurkey',
	'chicken': 'tempeh',
	'ground beef': 'ground turkey',
	'ground pork': 'ground jackfruit',
	'bacon': 'turkey bacon',
	'sausage': 'turkey sausage',
	'white rice': 'brown rice',
	'rice': 'brown rice',
	'pasta': 'whole-grain pasta',
	'spaghetti': 'whole-grain spaghetti',
	'bread': 'whole-grain bread',
	'penne': 'whole-grain penne',
	'flour tortilla': 'corn tortilla',
	'tortilla' : 'lettuce',
	'butter': 'margarine',
	'sour cream': 'greek yogurt',
	'croutons': 'almonds',
	'sugar': 'stevia',
	'flour': 'coconut flour',
	'salt': 'himalayan salt',
	'breadcrumbs': 'chia seeds',
	'bread crumbs': 'chia seeds',
	'bread crumb': 'chia seed',
	'chocolate chips': 'cocoa nibs',
	'iceberg': 'romaine',
	'ranch dressing': 'olive oil',
	'ranch' :'olive oil',
	'peanut butter': 'almond butter',
	'milk' : 'almond milk',
	# 'oil' : 'vegetable oil',
	'soy sauce':'coconut aminos',
	# 'frying' : 'grilling or baking',
	# 'fried':'grilled or baked',
	# 'fry':'grill or bake',
	'cornstarch':'wheat flour',
	'chocolate':'dark-chocolate'
}

# original to nonhealthy
to_unhealthydict={
	'sugar ':'corn syrup',
	'olive oil':'lard',
	'coconut oil':'lard',
	'vegetable oil':'lard',
	' oil' : 'lard',
	'plain':'glazed',
	'bread':'donut',
	'milk' : 'heavy cream',
	'veggie burger':'burger',
	'veggie':'beef',
	'water':'sugarwater',
	'dark chocolate':'milk chocolate',
	# 'bake':'fry',
	'grill':'fry',
	'red pepper':'pepperoni',
	'salt':'salt coated in oil',
	'carrots':'licorice',
	'carrot':'licorice',
	'flour':'cornstarch',
	'egg':'artificial egg',
	# 'green onion':' fried green onion',
	# 'yellow onion':'fried yellow onion',
	# ''
	'onion':'fried onion',
	'green pepper':'fried green pepper'

}

#style of cuisine: Sicilian Cuisine (Sicily in Italy)
to_siciliandict={
	'meatsauce': 'ragu',
	'tomato': 'Pachino tomato',
	'noodles': 'spaghetti',
	'broth': 'soup',
	'tilapi': 'sea bream',
	'salmon': 'bluefin tuna',
	'blueberry':'mulberry',
	'cilantro': 'mint',
	'shark': 'swordfish',
	'marlin': 'swordfish',
	'carp':'sea bream',
	'donut': 'cannoli',
	'red wine': 'Marsala',
	'wine': 'Marsala',
	'green bean': 'fava bean',
	'lima bean': 'fava bean',
	'salt': 'sea salt',
	'herring': 'sardines', 
	'pesto': 'zogghiu',
	'quinoa': 'couscous', 
	'vegetable oil': 'olive oil',
	'cocunut oil': 'olive oil',
	'regular oil':'olive oil',
	'any oil':'olive oil',
	'ground beef': 'ground veal',
	'ground turkey':'ground veal',
	'beef' :'lamb',
	'celery': 'fennels',
	'sorbert': 'granita',
	'flour': 'durum wheat/semolina flour',
	'orange': 'moro orange',
	'provolone': 'caciocavallo',
	'mozerella' :'caciocavallo',
	'american': 'pecorino',
	'chedder' :'caciocavallo',
	'parmesan': 'ricotta',
	'colby':'ricotta',
	'gruyere' :'maiorchino',
	'cottage': 'ricotta',
	'cream cheese' :'ricotta',
	'blue cheese' : 'gorgonzola',
	'meunster' : 'ragusano',
	'guda' : 'canestrato',
	'swiss': 'tuma',
	'feta':'ricotta',
	'garlic': 'Nubia Red Garlic',
	'chocolate': 'Modica chocolate',
	'lemon' :'Siracusa lemon',
	# 'grill': 'fry',
	'ice cream':'gelato',
	'garam masala':'cinnamon',
	'masala curry':'ragu',	
	'curry':'ragu',
	'tumeric':'saffron',
	'basmati rice':'orzo',
	'white rice':'orzo',
	'brown rice':'orzo',
	'cardamom pods':'fava beans',
	'green onion':'Giarratana Onion',
	'yellow onion':"Giarratana Onion",
	'red onion': 'Giarratana Onion',
	'onion':'Giarratana Onion',
	'iceberg lettuce':'arugula',
	'romaine lettuce':'arugula',
	'lettuce':'arugula',
	'soy sauce':'olive oil or Salmoriglio',
	'mushroom':'porcini mushroom',
	'tamarind pulp':'chickpeas',
	'tamarind':'chickpeas',
	'coriander':'menta',
}

to_korean_dict={
  'vegetable oil':'sesame oil',
  'olive oil':'sesame oil',
  'cocunut oil':'sesame oil',
  'oil': 'sesame oil',
  'ketchup': 'gochujang',
  'salt': 'soy sauce',
  'pickles': 'kimchi',
  'pot roast': 'galbijjim',
  'maruchan': 'shin',
  'omelette': 'steamed egg',
  'pancakes': 'hoddeok',
  'noodle' : 'rice noodles',
} 

